version: 0.1.{build}
image: Visual Studio 2017
environment:
  matrix:
    - configuration: Release
matrix:
  fast_finish: false
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: normal
artifacts:
- path: bin\**\*.*
