version: 0.1.{build}
image: Visual Studio 2017
environment:
  matrix:
    - configuration: Release
matrix:
  fast_finish: false
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: normal
after_build:
  - ps: nuget pack InvoiceCaptureLib.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
- path: InvoiceCaptureLib\bin\**\*.dll
